[package]
name = "scylla"
version = "0.0.1"
edition = "2018"
description = "Async CQL driver for Rust, optimized for Scylla."
repository = "https://github.com/psarna/scylla-rust-driver"
readme = "../README.md"
keywords = ["database", "scylla", "cql"]
categories = ["database"]

[dependencies]
anyhow = "1.0.33"
byteorder = "1.3.4"
bytes = "0.6.0"
num_enum = "0.5"
lz4-compression = "0.7.0"
tokio = { version = "0.3.0", features = ["net", "time", "io-util", "sync", "rt", "macros"] }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false
